apiVersion: v2
name: unikorn-ui
description: A Helm chart for deploying Unikorn UI

type: application

version: v1.1.0-rc1
appVersion: v1.1.0-rc1

icon: https://assets.unikorn-cloud.org/assets/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: v0.1.15
  repository: https://nscaledev.github.io/uni-helm-common
